insert into estado (estadoID,nome,sigla) values(2,"Alagoas","AL");
insert into estado (estadoID,nome,sigla) values(3,"Amazonas","AM");
insert into estado (estadoID,nome,sigla) values(4,"Amapá","AP");
insert into estado (estadoID,nome,sigla) values(5,"Bahia","BA");
insert into estado (estadoID,nome,sigla) values(6,"Cear·","CE");
insert into estado (estadoID,nome,sigla) values(7,"Distrito Federal","DF");
insert into estado (estadoID,nome,sigla) values(8,"Espírito Santo","ES");
insert into estado (estadoID,nome,sigla) values(9,"Goiás","GO");
insert into estado (estadoID,nome,sigla) values(10,"Maranãoo","MA");
insert into estado (estadoID,nome,sigla) values(11,"Minas Gerais","MG");
insert into estado (estadoID,nome,sigla) values(12,"Mato Grosso do Sul","MS");
insert into estado (estadoID,nome,sigla) values(13,"Mato Grosso","MT");
insert into estado (estadoID,nome,sigla) values(14,"Pará","PA");
insert into estado (estadoID,nome,sigla) values(15,"Paraíba","PB");
insert into estado (estadoID,nome,sigla) values(16,"Pernambuco","PE");
insert into estado (estadoID,nome,sigla) values(17,"Piauí","PI");
insert into estado (estadoID,nome,sigla) values(18,"Paraná","PR");
insert into estado (estadoID,nome,sigla) values(19,"Rio de Janeiro","RJ");
insert into estado (estadoID,nome,sigla) values(20,"Rio Grande do Norte","RN");
insert into estado (estadoID,nome,sigla) values(21,"Rondônia","RO");
insert into estado (estadoID,nome,sigla) values(22,"Roraima","RR");
insert into estado (estadoID,nome,sigla) values(23,"Rio Grande do Sul","RS");
insert into estado (estadoID,nome,sigla) values(24,"Santa Catarina","SC");
insert into estado (estadoID,nome,sigla) values(25,"Sergipe","SE");
insert into estado (estadoID,nome,sigla) values(26,"São Paulo","SP");
insert into estado (estadoID,nome,sigla) values(27,"Tocantins","TO");